# Generated by Django 6.0.2 on 2026-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('asks', models.TextField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('worktime', models.CharField(max_length=100)),
            ],
        ),
    ]
