# Generated by Django 6.0.2 on 2026-02-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_activity_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytitle',
            name='time',
        ),
    ]
