# Generated by Django 6.0.2 on 2026-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='category',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
